#!/bin/sh
DOCKER_HOST_IP=$(route -n | awk '/UG[ \t]/{print $2}')
echo ping ${HOSTNAME:=localhost} every ${TIMEOUT:=300} sec

while true; do echo "$STATSDLOC:$(curl -s ${HOSTNAME}:7801/stats | jq -r '.average_response_time_sec'):g" | nc -w 1 -u $DOCKER_HOST_IP 8125; sleep ${TIMEOUT}; done;
